import { Badge, DemoNotice, PageHeader, Panel, Stat } from "../components/Ui";

export function DashboardPage() {
  return <><PageHeader eyebrow="MULTI-ROLE DASHBOARD" title="One view across work and settlement" description="Fixture cards demonstrate the publisher, agent, and committee perspectives without claiming deployed activity." /><DemoNotice /><div className="stats-grid"><Stat label="Draft tasks" value="2" note="Local fixture" /><Stat label="Active agents" value="1" note="Local fixture" tone="cyan" /><Stat label="Verified transactions" value="0" note="External evidence required" tone="amber" /></div><div className="two-column"><Panel><h2>My work</h2><div className="activity-list"><div><Badge tone="cyan">WORKING</Badge><strong>Normalize product feedback</strong><span>Submission due in 24 hours</span></div><div><Badge tone="neutral">DRAFT</Badge><strong>Research market brief</strong><span>Escrow not submitted</span></div></div></Panel><Panel><h2>Request trace lookup</h2><input placeholder="Paste a request ID" /><button className="button button-ghost">Lookup unavailable offline</button><p className="muted">Production lookup will correlate API, event, match, training, and transaction records.</p></Panel></div></>;
}

export function CommitteePage() {
  return <><PageHeader eyebrow="ARBITRATION COMMITTEE" title="Conflict-aware case queue" description="Three valid seats, immutable votes, and a two-vote ruling threshold are enforced by the settlement boundary." /><DemoNotice /><div className="committee-grid"><Panel className="seat-card"><Badge tone="amber">ACTION REQUIRED</Badge><h2>Case assignment demo</h2><p>Review relationships before opening the evidence packet.</p><button className="button button-primary">Declare no conflict</button></Panel><Panel className="seat-card"><Badge tone="neutral">NO TASKS</Badge><h2>Replacement queue</h2><p>No externally verified cases are assigned.</p></Panel><Panel className="seat-card"><Badge tone="cyan">RULE</Badge><h2>2 of 3</h2><p>A ruling forms immediately when either outcome reaches two valid votes.</p></Panel></div></>;
}

export function OpsPage() {
  return <><PageHeader eyebrow="READ-ONLY AI OPS" title="Observe first. Suggest second." description="This surface may explain incidents, but cannot deploy, scale, transfer funds, vote, or change production resources." /><div className="ops-grid"><Panel><div className="panel-heading"><h2>Runtime readiness</h2><Badge tone="amber">LOCAL ONLY</Badge></div>{[["Transaction Engine", "Local build pending full gate"], ["Go matcher", "Local tests available"], ["CTR trainer", "Local tests available"], ["AWS workload", "Not deployed"], ["Cloudflare", "Not deployed"]].map(([name, state]) => <div className="health-row" key={name}><strong>{name}</strong><span>{state}</span></div>)}</Panel><Panel><div className="panel-heading"><h2>Model lifecycle</h2><Badge tone="neutral">NO ACTIVE MODEL</Badge></div><div className="model-stage"><span>training samples</span><span>candidate</span><span>manual approval</span><span>active</span></div><p className="muted">A local logistic-regression protocol exists. ECS execution and model readback remain external work.</p></Panel><Panel className="span-two"><h2>AI Ops recommendation contract</h2><div className="recommendation"><div><span>Observed symptom</span><strong>No live telemetry</strong></div><div><span>Evidence</span><strong>AWS and Cloudflare are not connected to this page</strong></div><div><span>Recommended action</span><strong>Complete read-only inventory before deployment</strong></div><div><span>Uncertainty</span><strong>High until external readback exists</strong></div></div></Panel></div></>;
}
